/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import domino.Ficha;
import draw.FichaDraw;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author HP
 */
public class PanelFichas extends javax.swing.JPanel {

    private FichaDraw fichaDraw;

    /**
     * Creates new form NewJPanel
     */
    public PanelFichas() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        this.fichaDraw = new FichaDraw(this.getHeight(),
                this.getWidth());
        Ficha ficha = new Ficha(6, 6);

        //ficha horizontal
        int x = 200;
        int y = 200;
        fichaDraw.dibujarFichaHorizontal(x, y, ficha, g);

        //ficha vertical
        x = 400;
        y = 400;
        fichaDraw.dibujarFichaVertical(x, y, ficha, g);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
