/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import domino.Ficha;
import dto.FichaDTO;
import dto.Orientacion;
import draw.FichaDraw;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HP
 */
public class PanelFichasJugador extends javax.swing.JPanel {

    private FichaDraw fichaDraw;
    private List<Ficha> fichas;
    private Ficha fichaSeleccionada;

    /**
     * Creates new form FichasJugador
     */
    public PanelFichasJugador(List<Ficha> fichas) {
        initComponents();
        this.fichaDraw = new FichaDraw(50);
        this.fichas = fichas;
//        this.fichas = new ArrayList<>();
//        fichas.add(new Ficha(1, 3));
//        fichas.add(new Ficha(1, 1));
//        fichas.add(new Ficha(2, 3));
//        fichas.add(new Ficha(3, 3));
//        fichas.add(new Ficha(4, 5));
//        fichas.add(new Ficha(6, 3));
//        fichas.add(new Ficha(1, 2));
        this.fichaSeleccionada = null;
    }

    private void seleccionarFicha(int x, int y) {
        for (Ficha ficha : fichas) {
            int xFicha = 60 + fichas.indexOf(ficha) * 100;
            int yFicha = 10;
            if (x >= xFicha && x <= xFicha + fichaDraw.getDimensionCuadrado()
                    && y >= yFicha && y <= yFicha + 2 * fichaDraw.getDimensionCuadrado()) {
                fichaSeleccionada = ficha;
                repaint();
                System.out.println("Ficha seleccionada jugador: " + ficha);
            }
        }
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        int x = 60;
        int y = 10;
        for (int i = 0; i < fichas.size(); i++) {
            FichaDTO fichaDTO = new FichaDTO(fichas.get(i), x, y, Orientacion.VERTICAL);
            fichaDraw.dibujarFichaVertical(fichaDTO, g);
            x += 100;
        }

        if (fichaSeleccionada != null) {
            int xFichaSeleccionada = 60 + fichas.indexOf(fichaSeleccionada) * 100;
            int yFichaSeleccionada = 10;
            g.setColor(Color.RED);
            g.drawRoundRect(xFichaSeleccionada, yFichaSeleccionada,
                    fichaDraw.getDimensionCuadrado(), fichaDraw.getDimensionCuadrado(), 6, 6);
            yFichaSeleccionada = 60;
            g.drawRoundRect(xFichaSeleccionada, yFichaSeleccionada,
                    fichaDraw.getDimensionCuadrado(), fichaDraw.getDimensionCuadrado(), 6, 6);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(60, 63, 65));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        seleccionarFicha(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
